export const RELAY_IPC_CHANNELS = {
  GET_APP_STATUS: 'relay:get-app-status',
  GET_DASHBOARD_STATE: 'relay:get-dashboard-state',
  LIST_PROJECTS: 'relay:list-projects',
  GET_PROJECT: 'relay:get-project',
  CREATE_PROJECT: 'relay:create-project',
  UPDATE_PROJECT: 'relay:update-project',
  ARCHIVE_PROJECT: 'relay:archive-project',
  UNARCHIVE_PROJECT: 'relay:unarchive-project',
  CAN_DELETE_PROJECT: 'relay:can-delete-project',
  DELETE_PROJECT: 'relay:delete-project',
  LIST_PAIRS: 'relay:list-pairs',
  GET_PAIR: 'relay:get-pair',
  CREATE_PAIR: 'relay:create-pair',
  UPDATE_PAIR: 'relay:update-pair',
  REBIND_PAIR_PLANNER: 'relay:rebind-pair-planner',
  REBIND_PAIR_WORKER: 'relay:rebind-pair-worker',
  DETACH_PAIR_RUNTIME: 'relay:detach-pair-runtime',
  START_PAIR: 'relay:start-pair',
  LOAD_AND_ACTIVATE_PAIR: 'relay:load-and-activate-pair',
  PAUSE_PAIR: 'relay:pause-pair',
  RESUME_PAIR: 'relay:resume-pair',
  STOP_PAIR: 'relay:stop-pair',
  ARCHIVE_PAIR: 'relay:archive-pair',
  UNARCHIVE_PAIR: 'relay:unarchive-pair',
  CAN_DELETE_PAIR: 'relay:can-delete-pair',
  DELETE_PAIR: 'relay:delete-pair',
  LIST_RUNTIME_SESSIONS: 'relay:list-runtime-sessions',
  REGISTER_RUNTIME_SESSION: 'relay:register-runtime-session',
  DISCOVER_RUNTIME: 'relay:discover-runtime',
  INSPECT_RUNTIME: 'relay:inspect-runtime',
  ACTIVATE_RUNTIME: 'relay:activate-runtime',
  OPEN_RUNTIME_SESSION: 'relay:open-runtime-session',
  RECOVER_RUNTIME: 'relay:recover-runtime',
  DETACH_RUNTIME: 'relay:detach-runtime',
  ARCHIVE_RUNTIME_SESSION: 'relay:archive-runtime-session',
  UNARCHIVE_RUNTIME_SESSION: 'relay:unarchive-runtime-session',
  CAN_DELETE_RUNTIME_SESSION: 'relay:can-delete-runtime-session',
  DELETE_RUNTIME_SESSION: 'relay:delete-runtime-session',
  LIST_ASSIGNMENTS: 'relay:list-assignments',
  GET_ASSIGNMENT_DETAIL: 'relay:get-assignment-detail',
  CREATE_ASSIGNMENT: 'relay:create-assignment',
  CREATE_AND_DISPATCH_ASSIGNMENT: 'relay:create-and-dispatch-assignment',
  DISPATCH_ASSIGNMENT: 'relay:dispatch-assignment',
  COMPLETE_ASSIGNMENT: 'relay:complete-assignment',
  DELIVER_HANDOFF: 'relay:deliver-handoff',
  RESOLVE_AMBIGUOUS_DELIVERY: 'relay:resolve-ambiguous-delivery',
  LIST_EVENTS: 'relay:list-events',
  QUERY_EVENTS: 'relay:query-events',
  LIST_ACTIVITIES: 'relay:list-activities',
  RUN_ARCHIVE_CYCLE: 'relay:run-archive-cycle',
  GET_ARCHIVE_POLICY: 'relay:get-archive-policy',
  SET_ARCHIVE_POLICY: 'relay:set-archive-policy',
  CLEAR_LOGS: 'relay:clear-logs',
  GET_STORAGE_ACCOUNTING: 'relay:get-storage-accounting',
  EXPORT_AUDIT_DATA: 'relay:export-audit-data',
  GET_AUXILIARY_LOGS_INFO: 'relay:get-auxiliary-logs-info',
  READ_AUXILIARY_LOG: 'relay:read-auxiliary-log',
  CLEAR_AUXILIARY_LOG: 'relay:clear-auxiliary-log',
  LIST_ATTENTION_ITEMS: 'relay:list-attention-items',
  ACKNOWLEDGE_ATTENTION_ITEM: 'relay:acknowledge-attention-item',
  RUN_SUPERVISION_TICK: 'relay:run-supervision-tick',
  SEED_DEMO_ENVIRONMENT: 'relay:seed-demo-environment',
  CLEAR_DATABASE: 'relay:clear-database',

  // Add Project Workflow
  SELECT_PROJECT_FOLDER: 'relay:select-project-folder',
  RESOLVE_CHATGPT_PROJECT: 'relay:resolve-chatgpt-project',
  DISCOVER_CHATGPT_PLANNER: 'relay:discover-chatgpt-planner',
  DISCOVER_OPENCODE_SESSIONS: 'relay:discover-opencode-sessions',
  ENUMERATE_CHATGPT_CONVERSATIONS: 'relay:enumerate-chatgpt-conversations',
  ENUMERATE_WORKER_CHOICES: 'relay:enumerate-worker-choices',
  ADOPT_OPENCODE_SESSION: 'relay:adopt-opencode-session',
  CREATE_OPENCODE_WORKER_SESSION: 'relay:create-opencode-worker-session',
  CREATE_CHATGPT_PLANNER_SESSION: 'relay:create-chatgpt-planner-session',
  PROVISION_PAIR_WITH_NEW_SESSIONS: 'relay:provision-pair-with-new-sessions',
  FINALIZE_PROJECT_SETUP: 'relay:finalize-project-setup',
  GET_DIAGNOSTICS_REPORT: 'relay:get-diagnostics-report',

  /* --- Phase 1 Health (read-only) -----------------------------------------
   *
   * These channels only READ persisted health state. No detector runs, no
   * provider is contacted, and no subprocess is spawned by any of them.
   */
  GET_HEALTH_SUMMARY: 'relay:get-health-summary',
  LIST_HEALTH_INCIDENTS: 'relay:list-health-incidents',
  GET_HEALTH_INCIDENT: 'relay:get-health-incident',
  ACKNOWLEDGE_HEALTH_INCIDENT: 'relay:acknowledge-health-incident',
  GENERATE_HEALTH_HANDOFF_REPORT: 'relay:generate-health-handoff-report',
  COPY_DIAGNOSTIC_REPORT: 'relay:copy-diagnostic-report',

  // Provider Integration & Capability Model
  LIST_INTEGRATIONS: 'relay:list-integrations',
  VERIFY_INTEGRATION: 'relay:verify-integration',
  RECHECK_ALL_INTEGRATIONS: 'relay:recheck-all-integrations',
  ADD_INTEGRATION: 'relay:add-integration',
  UPDATE_INTEGRATION: 'relay:update-integration',
  DELETE_INTEGRATION: 'relay:delete-integration',
  TOGGLE_INTEGRATION_ENABLED: 'relay:toggle-integration-enabled',
  SET_DEFAULT_INTEGRATION: 'relay:set-default-integration',
  GET_DEFAULT_PLANNER_INTEGRATION: 'relay:get-default-planner-integration',
  GET_DEFAULT_WORKER_INTEGRATION: 'relay:get-default-worker-integration',
  UPDATE_PLANNER_CONVERSATION_URL: 'relay:update-planner-conversation-url',
  TEST_INTEGRATION: 'relay:test-integration',
  SET_PROJECT_INTEGRATION_OVERRIDE: 'relay:set-project-integration-override',
  GET_PROJECT_INTEGRATION_OVERRIDE: 'relay:get-project-integration-override',
  LIST_PROJECT_INTEGRATION_OVERRIDES: 'relay:list-project-integration-overrides',

  // Worker AI Model Configuration & Application
  GET_SUPPORTED_MODELS: 'relay:get-supported-models',
  GET_EFFECTIVE_MODEL_CONFIG: 'relay:get-effective-model-config',
  SET_GLOBAL_MODEL_DEFAULT: 'relay:set-global-model-default',
  SET_PROJECT_MODEL_OVERRIDE: 'relay:set-project-model-override',
  CLEAR_PROJECT_MODEL_OVERRIDE: 'relay:clear-project-model-override',
  SET_PAIR_MODEL_OVERRIDE: 'relay:set-pair-model-override',
  CLEAR_PAIR_MODEL_OVERRIDE: 'relay:clear-pair-model-override',
} as const;

export type RelayIpcChannel = (typeof RELAY_IPC_CHANNELS)[keyof typeof RELAY_IPC_CHANNELS];
