export const RELAY_IPC_CHANNELS = {
  GET_APP_STATUS: 'relay:get-app-status',
  GET_DASHBOARD_STATE: 'relay:get-dashboard-state',
  LIST_PROJECTS: 'relay:list-projects',
  GET_PROJECT: 'relay:get-project',
  CREATE_PROJECT: 'relay:create-project',
  UPDATE_PROJECT: 'relay:update-project',
  ARCHIVE_PROJECT: 'relay:archive-project',
  UNARCHIVE_PROJECT: 'relay:unarchive-project',
  CAN_DELETE_PROJECT: 'relay:can-delete-project',
  DELETE_PROJECT: 'relay:delete-project',
  LIST_PAIRS: 'relay:list-pairs',
  GET_PAIR: 'relay:get-pair',
  CREATE_PAIR: 'relay:create-pair',
  UPDATE_PAIR: 'relay:update-pair',
  REBIND_PAIR_PLANNER: 'relay:rebind-pair-planner',
  REBIND_PAIR_WORKER: 'relay:rebind-pair-worker',
  DETACH_PAIR_RUNTIME: 'relay:detach-pair-runtime',
  START_PAIR: 'relay:start-pair',
  PAUSE_PAIR: 'relay:pause-pair',
  RESUME_PAIR: 'relay:resume-pair',
  STOP_PAIR: 'relay:stop-pair',
  ARCHIVE_PAIR: 'relay:archive-pair',
  UNARCHIVE_PAIR: 'relay:unarchive-pair',
  CAN_DELETE_PAIR: 'relay:can-delete-pair',
  DELETE_PAIR: 'relay:delete-pair',
  LIST_RUNTIME_SESSIONS: 'relay:list-runtime-sessions',
  REGISTER_RUNTIME_SESSION: 'relay:register-runtime-session',
  DISCOVER_RUNTIME: 'relay:discover-runtime',
  INSPECT_RUNTIME: 'relay:inspect-runtime',
  RECOVER_RUNTIME: 'relay:recover-runtime',
  DETACH_RUNTIME: 'relay:detach-runtime',
  ARCHIVE_RUNTIME_SESSION: 'relay:archive-runtime-session',
  UNARCHIVE_RUNTIME_SESSION: 'relay:unarchive-runtime-session',
  CAN_DELETE_RUNTIME_SESSION: 'relay:can-delete-runtime-session',
  DELETE_RUNTIME_SESSION: 'relay:delete-runtime-session',
  LIST_ASSIGNMENTS: 'relay:list-assignments',
  CREATE_ASSIGNMENT: 'relay:create-assignment',
  DISPATCH_ASSIGNMENT: 'relay:dispatch-assignment',
  COMPLETE_ASSIGNMENT: 'relay:complete-assignment',
  DELIVER_HANDOFF: 'relay:deliver-handoff',
  RESOLVE_AMBIGUOUS_DELIVERY: 'relay:resolve-ambiguous-delivery',
  LIST_EVENTS: 'relay:list-events',
  LIST_ATTENTION_ITEMS: 'relay:list-attention-items',
  ACKNOWLEDGE_ATTENTION_ITEM: 'relay:acknowledge-attention-item',
  RUN_SUPERVISION_TICK: 'relay:run-supervision-tick',
  SEED_DEMO_ENVIRONMENT: 'relay:seed-demo-environment',
  CLEAR_DATABASE: 'relay:clear-database',

  // Add Project Workflow
  SELECT_PROJECT_FOLDER: 'relay:select-project-folder',
  RESOLVE_CHATGPT_PROJECT: 'relay:resolve-chatgpt-project',
  DISCOVER_CHATGPT_PLANNER: 'relay:discover-chatgpt-planner',
  DISCOVER_OPENCODE_SESSIONS: 'relay:discover-opencode-sessions',
  FINALIZE_PROJECT_SETUP: 'relay:finalize-project-setup',
} as const;

export type RelayIpcChannel = (typeof RELAY_IPC_CHANNELS)[keyof typeof RELAY_IPC_CHANNELS];
